# Copyright (c) 2012, Vehbi Sinan Tunalioglu <vst@vsthost.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# - Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
#
# - Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in
#   the documentation and/or other materials provided with the
#   distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

__version__ = (0, 0, 0, "dev", 0)

from collections import OrderedDict


class Country(object):
    """
    Provides the canonical representation of a country object and
    further functionality such as querying.
    """

    _LOOKUP_TABLE = {"code_2": dict(), "code_3": dict(), "enum": dict(),
                     "name": dict()}
    """
    Provides a lookup table mainly for :attr:`get` class method.
    """

    DB = OrderedDict()
    """
    Provides the country database as an ordered dictionary.
    """

    def __init__(self, code_2, code_3, enum, code_fips, continent, currency,
                 tld, name, capital, postal_code_format, postal_code_regex,
                 phone_prefixes):
        # Save object attributes:
        self.code_2 = code_2
        self.code_3 = code_3
        self.enum = enum
        self.code_fips = code_fips
        self.continent = continent
        self.currency = currency
        self.tld = tld
        self.name = name
        self.capital = capital
        self.postal_code_format = postal_code_format
        self.postal_code_regex = postal_code_regex
        self.phone_prefixes = phone_prefixes

    def __repr__(self):
        return self.name

    @classmethod
    def get(cls, identifier):
        """
        Queries the :attr:`Country._LOOKUP_TABLE` for the identifier
        provided and returns the country object if found, ``None``
        otherwise.
        """
        return cls._LOOKUP_TABLE["code_2"].get(identifier) or \
               cls._LOOKUP_TABLE["code_3"].get(identifier) or \
               cls._LOOKUP_TABLE["enum"].get(identifier) or \
               cls._LOOKUP_TABLE["name"].get(identifier.upper())

    @classmethod
    def put(cls, *args):
        """
        Inserts or overrides a country in the DB.

        Note that this method indexes every country by its
        :attr:`code_2`, :attr:`code_3`, :attr:`enum` and :attr:`name`
        attributes.
        """
        # Get the tuples by combining existing ones and new ones:
        tuples = cls.DB.items() + [(arg.code_2, arg) for arg in args]

        # Reset the Database:
        cls.DB = OrderedDict(sorted(tuples, key=lambda x: x[0]))

        # Reset the lookup table (code_2 as the identifier):
        cls._LOOKUP_TABLE["code_2"] = dict(tuples)

        # Reset the lookup table (code_3 as the identifier):
        recoded_items = [(item[1].code_3, item[1]) for item in tuples]
        cls._LOOKUP_TABLE["code_3"] = dict(recoded_items)

        # Reset the lookup table (enum as the identifier):
        enumed_items = [(item[1].enum, item[1]) for item in tuples]
        cls._LOOKUP_TABLE["enum"] = dict(enumed_items)

        # Reset the lookup table (name as the identifier):
        named_items = [(item[1].name.upper(), item[1]) for item in tuples]
        cls._LOOKUP_TABLE["name"] = dict(named_items)


#######################
# DATABASE POPULATION #
#######################

Country.put(*[Country("AD", "AND", "020", "AN", "EU", "EUR", ".ad",
                      "Andorra", "Andorra la Vella",
                      "AD###", "^(?:AD)*(\d{3})$", ["376"]),
              Country("AD", "AND", "020", "AN", "EU", "EUR", ".ad",
                      "Andorra", "Andorra la Vella",
                      "AD###", "^(?:AD)*(\d{3})$", ["376"]),
              Country("AE", "ARE", "784", "AE", "AS", "AED", ".ae",
                      "United Arab Emirates", "Abu Dhabi",
                      "", "", ["971"]),
              Country("AF", "AFG", "004", "AF", "AS", "AFN", ".af",
                      "Afghanistan", "Kabul",
                      "", "", ["93"]),
              Country("AG", "ATG", "028", "AC", "NA", "XCD", ".ag",
                      "Antigua and Barbuda", "St. John's",
                      "", "", ["1-268"]),
              Country("AI", "AIA", "660", "AV", "NA", "XCD", ".ai",
                      "Anguilla", "The Valley",
                      "", "", ["1-264"]),
              Country("AL", "ALB", "008", "AL", "EU", "ALL", ".al",
                      "Albania", "Tirana",
                      "", "", ["355"]),
              Country("AM", "ARM", "051", "AM", "AS", "AMD", ".am",
                      "Armenia", "Yerevan",
                      "######", "^(\d{6})$", ["374"]),
              Country("AO", "AGO", "024", "AO", "AF", "AOA", ".ao",
                      "Angola", "Luanda",
                      "", "", ["244"]),
              Country("AQ", "ATA", "010", "AY", "AN", "", ".aq",
                      "Antarctica", "",
                      "", "", [""]),
              Country("AR", "ARG", "032", "AR", "SA", "ARS", ".ar",
                      "Argentina", "Buenos Aires",
                      "@####@@@", "^([A-Z]\d{4}[A-Z]{3})$", ["54"]),
              Country("AS", "ASM", "016", "AQ", "OC", "USD", ".as",
                      "American Samoa", "Pago Pago",
                      "", "", ["1-684"]),
              Country("AT", "AUT", "040", "AU", "EU", "EUR", ".at",
                      "Austria", "Vienna",
                      "####", "^(\d{4})$", ["43"]),
              Country("AU", "AUS", "036", "AS", "OC", "AUD", ".au",
                      "Australia", "Canberra",
                      "####", "^(\d{4})$", ["61"]),
              Country("AW", "ABW", "533", "AA", "NA", "AWG", ".aw",
                      "Aruba", "Oranjestad",
                      "", "", ["297"]),
              Country("AX", "ALA", "248", "", "EU", "EUR", ".ax",
                      "Aland Islands", "Mariehamn",
                      "", "", ["358-18"]),
              Country("AZ", "AZE", "031", "AJ", "AS", "AZN", ".az",
                      "Azerbaijan", "Baku",
                      "AZ ####", "^(?:AZ)*(\d{4})$", ["994"]),
              Country("BA", "BIH", "070", "BK", "EU", "BAM", ".ba",
                      "Bosnia and Herzegovina", "Sarajevo",
                      "#####", "^(\d{5})$", ["387"]),
              Country("BB", "BRB", "052", "BB", "NA", "BBD", ".bb",
                      "Barbados", "Bridgetown",
                      "BB#####", "^(?:BB)*(\d{5})$", ["1-246"]),
              Country("BD", "BGD", "050", "BG", "AS", "BDT", ".bd",
                      "Bangladesh", "Dhaka",
                      "####", "^(\d{4})$", ["880"]),
              Country("BE", "BEL", "056", "BE", "EU", "EUR", ".be",
                      "Belgium", "Brussels",
                      "####", "^(\d{4})$", ["32"]),
              Country("BF", "BFA", "854", "UV", "AF", "XOF", ".bf",
                      "Burkina Faso", "Ouagadougou",
                      "", "", ["226"]),
              Country("BG", "BGR", "100", "BU", "EU", "BGN", ".bg",
                      "Bulgaria", "Sofia",
                      "####", "^(\d{4})$", ["359"]),
              Country("BH", "BHR", "048", "BA", "AS", "BHD", ".bh",
                      "Bahrain", "Manama",
                      "####|###", "^(\d{3}\d?)$", ["973"]),
              Country("BI", "BDI", "108", "BY", "AF", "BIF", ".bi",
                      "Burundi", "Bujumbura",
                      "", "", ["257"]),
              Country("BJ", "BEN", "204", "BN", "AF", "XOF", ".bj",
                      "Benin", "Porto-Novo",
                      "", "", ["229"]),
              Country("BL", "BLM", "652", "TB", "NA", "EUR", ".gp",
                      "Saint Barthelemy", "Gustavia",
                      "### ###", "", ["590"]),
              Country("BM", "BMU", "060", "BD", "NA", "BMD", ".bm",
                      "Bermuda", "Hamilton",
                      "@@ ##", "^([A-Z]{2}\d{2})$", ["1-441"]),
              Country("BN", "BRN", "096", "BX", "AS", "BND", ".bn",
                      "Brunei", "Bandar Seri Begawan",
                      "@@####", "^([A-Z]{2}\d{4})$", ["673"]),
              Country("BO", "BOL", "068", "BL", "SA", "BOB", ".bo",
                      "Bolivia", "Sucre",
                      "", "", ["591"]),
              Country("BQ", "BES", "535", "", "NA", "USD", ".bq",
                      "Bonaire, Saint Eustatius and Saba", "",
                      "", "", ["599"]),
              Country("BR", "BRA", "076", "BR", "SA", "BRL", ".br",
                      "Brazil", "Brasilia",
                      "#####-###", "^(\d{8})$", ["55"]),
              Country("BS", "BHS", "044", "BF", "NA", "BSD", ".bs",
                      "Bahamas", "Nassau",
                      "", "", ["1-242"]),
              Country("BT", "BTN", "064", "BT", "AS", "BTN", ".bt",
                      "Bhutan", "Thimphu",
                      "", "", ["975"]),
              Country("BV", "BVT", "074", "BV", "AN", "NOK", ".bv",
                      "Bouvet Island", "",
                      "", "", [""]),
              Country("BW", "BWA", "072", "BC", "AF", "BWP", ".bw",
                      "Botswana", "Gaborone",
                      "", "", ["267"]),
              Country("BY", "BLR", "112", "BO", "EU", "BYR", ".by",
                      "Belarus", "Minsk",
                      "######", "^(\d{6})$", ["375"]),
              Country("BZ", "BLZ", "084", "BH", "NA", "BZD", ".bz",
                      "Belize", "Belmopan",
                      "", "", ["501"]),
              Country("CA", "CAN", "124", "CA", "NA", "CAD", ".ca",
                      "Canada", "Ottawa",
                      "@#@ #@#", "^([a-zA-Z]\d[a-zA-Z]\d[a-zA-Z]\d)$", ["1"]),
              Country("CC", "CCK", "166", "CK", "AS", "AUD", ".cc",
                      "Cocos Islands", "West Island",
                      "", "", ["61"]),
              Country("CD", "COD", "180", "CG", "AF", "CDF", ".cd",
                      "Democratic Republic of the Congo", "Kinshasa",
                      "", "", ["243"]),
              Country("CF", "CAF", "140", "CT", "AF", "XAF", ".cf",
                      "Central African Republic", "Bangui",
                      "", "", ["236"]),
              Country("CG", "COG", "178", "CF", "AF", "XAF", ".cg",
                      "Republic of the Congo", "Brazzaville",
                      "", "", ["242"]),
              Country("CH", "CHE", "756", "SZ", "EU", "CHF", ".ch",
                      "Switzerland", "Berne",
                      "####", "^(\d{4})$", ["41"]),
              Country("CI", "CIV", "384", "IV", "AF", "XOF", ".ci",
                      "Ivory Coast", "Yamoussoukro",
                      "", "", ["225"]),
              Country("CK", "COK", "184", "CW", "OC", "NZD", ".ck",
                      "Cook Islands", "Avarua",
                      "", "", ["682"]),
              Country("CL", "CHL", "152", "CI", "SA", "CLP", ".cl",
                      "Chile", "Santiago",
                      "#######", "^(\d{7})$", ["56"]),
              Country("CM", "CMR", "120", "CM", "AF", "XAF", ".cm",
                      "Cameroon", "Yaounde",
                      "", "", ["237"]),
              Country("CN", "CHN", "156", "CH", "AS", "CNY", ".cn",
                      "China", "Beijing",
                      "######", "^(\d{6})$", ["86"]),
              Country("CO", "COL", "170", "CO", "SA", "COP", ".co",
                      "Colombia", "Bogota",
                      "", "", ["57"]),
              Country("CR", "CRI", "188", "CS", "NA", "CRC", ".cr",
                      "Costa Rica", "San Jose",
                      "####", "^(\d{4})$", ["506"]),
              Country("CU", "CUB", "192", "CU", "NA", "CUP", ".cu",
                      "Cuba", "Havana",
                      "CP #####", "^(?:CP)*(\d{5})$", ["53"]),
              Country("CV", "CPV", "132", "CV", "AF", "CVE", ".cv",
                      "Cape Verde", "Praia",
                      "####", "^(\d{4})$", ["238"]),
              Country("CW", "CUW", "531", "UC", "NA", "ANG", ".cw",
                      "Curacao", "Willemstad",
                      "", "", ["599"]),
              Country("CX", "CXR", "162", "KT", "AS", "AUD", ".cx",
                      "Christmas Island", "Flying Fish Cove",
                      "####", "^(\d{4})$", ["61"]),
              Country("CY", "CYP", "196", "CY", "EU", "EUR", ".cy",
                      "Cyprus", "Nicosia",
                      "####", "^(\d{4})$", ["357"]),
              Country("CZ", "CZE", "203", "EZ", "EU", "CZK", ".cz",
                      "Czech Republic", "Prague",
                      "### ##", "^(\d{5})$", ["420"]),
              Country("DE", "DEU", "276", "GM", "EU", "EUR", ".de",
                      "Germany", "Berlin",
                      "#####", "^(\d{5})$", ["49"]),
              Country("DJ", "DJI", "262", "DJ", "AF", "DJF", ".dj",
                      "Djibouti", "Djibouti",
                      "", "", ["253"]),
              Country("DK", "DNK", "208", "DA", "EU", "DKK", ".dk",
                      "Denmark", "Copenhagen",
                      "####", "^(\d{4})$", ["45"]),
              Country("DM", "DMA", "212", "DO", "NA", "XCD", ".dm",
                      "Dominica", "Roseau",
                      "", "", ["1-767"]),
              Country("DO", "DOM", "214", "DR", "NA", "DOP", ".do",
                      "Dominican Republic", "Santo Domingo",
                      "#####", "^(\d{5})$", ["1-809", "1-829"]),
              Country("DZ", "DZA", "012", "AG", "AF", "DZD", ".dz",
                      "Algeria", "Algiers",
                      "#####", "^(\d{5})$", ["213"]),
              Country("EC", "ECU", "218", "EC", "SA", "USD", ".ec",
                      "Ecuador", "Quito",
                      "@####@", "^([a-zA-Z]\d{4}[a-zA-Z])$", ["593"]),
              Country("EE", "EST", "233", "EN", "EU", "EUR", ".ee",
                      "Estonia", "Tallinn",
                      "#####", "^(\d{5})$", ["372"]),
              Country("EG", "EGY", "818", "EG", "AF", "EGP", ".eg",
                      "Egypt", "Cairo",
                      "#####", "^(\d{5})$", ["20"]),
              Country("EH", "ESH", "732", "WI", "AF", "MAD", ".eh",
                      "Western Sahara", "El-Aaiun",
                      "", "", ["212"]),
              Country("ER", "ERI", "232", "ER", "AF", "ERN", ".er",
                      "Eritrea", "Asmara",
                      "", "", ["291"]),
              Country("ES", "ESP", "724", "SP", "EU", "EUR", ".es",
                      "Spain", "Madrid",
                      "#####", "^(\d{5})$", ["34"]),
              Country("ET", "ETH", "231", "ET", "AF", "ETB", ".et",
                      "Ethiopia", "Addis Ababa",
                      "####", "^(\d{4})$", ["251"]),
              Country("FI", "FIN", "246", "FI", "EU", "EUR", ".fi",
                      "Finland", "Helsinki",
                      "#####", "^(?:FI)*(\d{5})$", ["358"]),
              Country("FJ", "FJI", "242", "FJ", "OC", "FJD", ".fj",
                      "Fiji", "Suva",
                      "", "", ["679"]),
              Country("FK", "FLK", "238", "FK", "SA", "FKP", ".fk",
                      "Falkland Islands", "Stanley",
                      "", "", ["500"]),
              Country("FM", "FSM", "583", "FM", "OC", "USD", ".fm",
                      "Micronesia", "Palikir",
                      "#####", "^(\d{5})$", ["691"]),
              Country("FO", "FRO", "234", "FO", "EU", "DKK", ".fo",
                      "Faroe Islands", "Torshavn",
                      "FO-###", "^(?:FO)*(\d{3})$", ["298"]),
              Country("FR", "FRA", "250", "FR", "EU", "EUR", ".fr",
                      "France", "Paris",
                      "#####", "^(\d{5})$", ["33"]),
              Country("GA", "GAB", "266", "GB", "AF", "XAF", ".ga",
                      "Gabon", "Libreville",
                      "", "", ["241"]),
              Country("GB", "GBR", "826", "UK", "EU", "GBP", ".uk",
                      "United Kingdom", "London",
                      "@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA",
                      "^(([A-Z]\d{2}[A-Z]{2})|"
                      "([A-Z]\d{3}[A-Z]{2})|"
                      "([A-Z]{2}\d{2}[A-Z]{2})|"
                      "([A-Z]{2}\d{3}[A-Z]{2})|"
                      "([A-Z]\d[A-Z]\d[A-Z]{2})|"
                      "([A-Z]{2}\d[A-Z]\d[A-Z]{2})|"
                      "(GIR0AA))$", ["44"]),
              Country("GD", "GRD", "308", "GJ", "NA", "XCD", ".gd",
                      "Grenada", "St. George's",
                      "", "", ["1-473"]),
              Country("GE", "GEO", "268", "GG", "AS", "GEL", ".ge",
                      "Georgia", "Tbilisi",
                      "####", "^(\d{4})$", ["995"]),
              Country("GF", "GUF", "254", "FG", "SA", "EUR", ".gf",
                      "French Guiana", "Cayenne",
                      "#####", "^((97)|(98)3\d{2})$", ["594"]),
              Country("GG", "GGY", "831", "GK", "EU", "GBP", ".gg",
                      "Guernsey", "St Peter Port",
                      "@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA",
                      "^(([A-Z]\d{2}[A-Z]{2})|([A-Z]\d{3}[A-Z]{2})|"
                      "([A-Z]{2}\d{2}[A-Z]{2})|([A-Z]{2}\d{3}[A-Z]{2})|"
                      "([A-Z]\d[A-Z]\d[A-Z]{2})|([A-Z]{2}\d[A-Z]\d[A-Z]{2})|"
                      "(GIR0AA))$", ["44-1481"]),
              Country("GH", "GHA", "288", "GH", "AF", "GHS", ".gh",
                      "Ghana", "Accra",
                      "", "", ["233"]),
              Country("GI", "GIB", "292", "GI", "EU", "GIP", ".gi",
                      "Gibraltar", "Gibraltar",
                      "", "", ["350"]),
              Country("GL", "GRL", "304", "GL", "NA", "DKK", ".gl",
                      "Greenland", "Nuuk",
                      "####", "^(\d{4})$", ["299"]),
              Country("GM", "GMB", "270", "GA", "AF", "GMD", ".gm",
                      "Gambia", "Banjul",
                      "", "", ["220"]),
              Country("GN", "GIN", "324", "GV", "AF", "GNF", ".gn",
                      "Guinea", "Conakry",
                      "", "", ["224"]),
              Country("GP", "GLP", "312", "GP", "NA", "EUR", ".gp",
                      "Guadeloupe", "Basse-Terre",
                      "#####", "^((97)|(98)\d{3})$", ["590"]),
              Country("GQ", "GNQ", "226", "EK", "AF", "XAF", ".gq",
                      "Equatorial Guinea", "Malabo",
                      "", "", ["240"]),
              Country("GR", "GRC", "300", "GR", "EU", "EUR", ".gr",
                      "Greece", "Athens",
                      "### ##", "^(\d{5})$", ["30"]),
              Country("GS", "SGS", "239", "SX", "AN", "GBP", ".gs",
                      "South Georgia and the South Sandwich Islands",
                      "Grytviken",
                      "", "", [""]),
              Country("GT", "GTM", "320", "GT", "NA", "GTQ", ".gt",
                      "Guatemala", "Guatemala City",
                      "#####", "^(\d{5})$", ["502"]),
              Country("GU", "GUM", "316", "GQ", "OC", "USD", ".gu",
                      "Guam", "Hagatna",
                      "969##", "^(969\d{2})$", ["1-671"]),
              Country("GW", "GNB", "624", "PU", "AF", "XOF", ".gw",
                      "Guinea-Bissau", "Bissau",
                      "####", "^(\d{4})$", ["245"]),
              Country("GY", "GUY", "328", "GY", "SA", "GYD", ".gy",
                      "Guyana", "Georgetown",
                      "", "", ["592"]),
              Country("HK", "HKG", "344", "HK", "AS", "HKD", ".hk",
                      "Hong Kong", "Hong Kong",
                      "", "", ["852"]),
              Country("HM", "HMD", "334", "HM", "AN", "AUD", ".hm",
                      "Heard Island and McDonald Islands", "",
                      "", "", [""]),
              Country("HN", "HND", "340", "HO", "NA", "HNL", ".hn",
                      "Honduras", "Tegucigalpa",
                      "@@####", "^([A-Z]{2}\d{4})$", ["504"]),
              Country("HR", "HRV", "191", "HR", "EU", "HRK", ".hr",
                      "Croatia", "Zagreb",
                      "HR-#####", "^(?:HR)*(\d{5})$", ["385"]),
              Country("HT", "HTI", "332", "HA", "NA", "HTG", ".ht",
                      "Haiti", "Port-au-Prince",
                      "HT####", "^(?:HT)*(\d{4})$", ["509"]),
              Country("HU", "HUN", "348", "HU", "EU", "HUF", ".hu",
                      "Hungary", "Budapest",
                      "####", "^(\d{4})$", ["36"]),
              Country("ID", "IDN", "360", "ID", "AS", "IDR", ".id",
                      "Indonesia", "Jakarta",
                      "#####", "^(\d{5})$", ["62"]),
              Country("IE", "IRL", "372", "EI", "EU", "EUR", ".ie",
                      "Ireland", "Dublin",
                      "", "", ["353"]),
              Country("IL", "ISR", "376", "IS", "AS", "ILS", ".il",
                      "Israel", "Jerusalem",
                      "#####", "^(\d{5})$", ["972"]),
              Country("IM", "IMN", "833", "IM", "EU", "GBP", ".im",
                      "Isle of Man", "Douglas, Isle of Man",
                      "@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA",
                      "^(([A-Z]\d{2}[A-Z]{2})|([A-Z]\d{3}[A-Z]{2})|"
                      "([A-Z]{2}\d{2}[A-Z]{2})|([A-Z]{2}\d{3}[A-Z]{2})|"
                      "([A-Z]\d[A-Z]\d[A-Z]{2})|([A-Z]{2}\d[A-Z]\d[A-Z]{2})|"
                      "(GIR0AA))$", ["44-1624"]),
              Country("IN", "IND", "356", "IN", "AS", "INR", ".in",
                      "India", "New Delhi",
                      "######", "^(\d{6})$", ["91"]),
              Country("IO", "IOT", "086", "IO", "AS", "USD", ".io",
                      "British Indian Ocean Territory", "Diego Garcia",
                      "", "", ["246"]),
              Country("IQ", "IRQ", "368", "IZ", "AS", "IQD", ".iq",
                      "Iraq", "Baghdad",
                      "#####", "^(\d{5})$", ["964"]),
              Country("IR", "IRN", "364", "IR", "AS", "IRR", ".ir",
                      "Iran", "Tehran",
                      "##########", "^(\d{10})$", ["98"]),
              Country("IS", "ISL", "352", "IC", "EU", "ISK", ".is",
                      "Iceland", "Reykjavik",
                      "###", "^(\d{3})$", ["354"]),
              Country("IT", "ITA", "380", "IT", "EU", "EUR", ".it",
                      "Italy", "Rome",
                      "#####", "^(\d{5})$", ["39"]),
              Country("JE", "JEY", "832", "JE", "EU", "GBP", ".je",
                      "Jersey", "Saint Helier",
                      "@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA",
                      "^(([A-Z]\d{2}[A-Z]{2})|([A-Z]\d{3}[A-Z]{2})|"
                      "([A-Z]{2}\d{2}[A-Z]{2})|([A-Z]{2}\d{3}[A-Z]{2})|"
                      "([A-Z]\d[A-Z]\d[A-Z]{2})|([A-Z]{2}\d[A-Z]\d[A-Z]{2})|"
                      "(GIR0AA))$", ["44-1534"]),
              Country("JM", "JAM", "388", "JM", "NA", "JMD", ".jm",
                      "Jamaica", "Kingston",
                      "", "", ["1-876"]),
              Country("JO", "JOR", "400", "JO", "AS", "JOD", ".jo",
                      "Jordan", "Amman",
                      "#####", "^(\d{5})$", ["962"]),
              Country("JP", "JPN", "392", "JA", "AS", "JPY", ".jp",
                      "Japan", "Tokyo",
                      "###-####", "^(\d{7})$", ["81"]),
              Country("KE", "KEN", "404", "KE", "AF", "KES", ".ke",
                      "Kenya", "Nairobi",
                      "#####", "^(\d{5})$", ["254"]),
              Country("KG", "KGZ", "417", "KG", "AS", "KGS", ".kg",
                      "Kyrgyzstan", "Bishkek",
                      "######", "^(\d{6})$", ["996"]),
              Country("KH", "KHM", "116", "CB", "AS", "KHR", ".kh",
                      "Cambodia", "Phnom Penh",
                      "#####", "^(\d{5})$", ["855"]),
              Country("KI", "KIR", "296", "KR", "OC", "AUD", ".ki",
                      "Kiribati", "Tarawa",
                      "", "", ["686"]),
              Country("KM", "COM", "174", "CN", "AF", "KMF", ".km",
                      "Comoros", "Moroni",
                      "", "", ["269"]),
              Country("KN", "KNA", "659", "SC", "NA", "XCD", ".kn",
                      "Saint Kitts and Nevis", "Basseterre",
                      "", "", ["1-869"]),
              Country("KP", "PRK", "408", "KN", "AS", "KPW", ".kp",
                      "North Korea", "Pyongyang",
                      "###-###", "^(\d{6})$", ["850"]),
              Country("KR", "KOR", "410", "KS", "AS", "KRW", ".kr",
                      "South Korea", "Seoul",
                      "SEOUL ###-###", "^(?:SEOUL)*(\d{6})$", ["82"]),
              Country("XK", "XKX", "0", "KV", "EU", "EUR", "",
                      "Kosovo", "Pristina",
                      "", "", [""]),
              Country("KW", "KWT", "414", "KU", "AS", "KWD", ".kw",
                      "Kuwait", "Kuwait City",
                      "#####", "^(\d{5})$", ["965"]),
              Country("KY", "CYM", "136", "CJ", "NA", "KYD", ".ky",
                      "Cayman Islands", "George Town",
                      "", "", ["1-345"]),
              Country("KZ", "KAZ", "398", "KZ", "AS", "KZT", ".kz",
                      "Kazakhstan", "Astana",
                      "######", "^(\d{6})$", ["7"]),
              Country("LA", "LAO", "418", "LA", "AS", "LAK", ".la",
                      "Laos", "Vientiane",
                      "#####", "^(\d{5})$", ["856"]),
              Country("LB", "LBN", "422", "LE", "AS", "LBP", ".lb",
                      "Lebanon", "Beirut",
                      "#### ####|####", "^(\d{4}(\d{4})?)$", ["961"]),
              Country("LC", "LCA", "662", "ST", "NA", "XCD", ".lc",
                      "Saint Lucia", "Castries",
                      "", "", ["1-758"]),
              Country("LI", "LIE", "438", "LS", "EU", "CHF", ".li",
                      "Liechtenstein", "Vaduz",
                      "####", "^(\d{4})$", ["423"]),
              Country("LK", "LKA", "144", "CE", "AS", "LKR", ".lk",
                      "Sri Lanka", "Colombo",
                      "#####", "^(\d{5})$", ["94"]),
              Country("LR", "LBR", "430", "LI", "AF", "LRD", ".lr",
                      "Liberia", "Monrovia",
                      "####", "^(\d{4})$", ["231"]),
              Country("LS", "LSO", "426", "LT", "AF", "LSL", ".ls",
                      "Lesotho", "Maseru",
                      "###", "^(\d{3})$", ["266"]),
              Country("LT", "LTU", "440", "LH", "EU", "LTL", ".lt",
                      "Lithuania", "Vilnius",
                      "LT-#####", "^(?:LT)*(\d{5})$", ["370"]),
              Country("LU", "LUX", "442", "LU", "EU", "EUR", ".lu",
                      "Luxembourg", "Luxembourg",
                      "####", "^(\d{4})$", ["352"]),
              Country("LV", "LVA", "428", "LG", "EU", "LVL", ".lv",
                      "Latvia", "Riga",
                      "LV-####", "^(?:LV)*(\d{4})$", ["371"]),
              Country("LY", "LBY", "434", "LY", "AF", "LYD", ".ly",
                      "Libya", "Tripolis",
                      "", "", ["218"]),
              Country("MA", "MAR", "504", "MO", "AF", "MAD", ".ma",
                      "Morocco", "Rabat",
                      "#####", "^(\d{5})$", ["212"]),
              Country("MC", "MCO", "492", "MN", "EU", "EUR", ".mc",
                      "Monaco", "Monaco",
                      "#####", "^(\d{5})$", ["377"]),
              Country("MD", "MDA", "498", "MD", "EU", "MDL", ".md",
                      "Moldova", "Chisinau",
                      "MD-####", "^(?:MD)*(\d{4})$", ["373"]),
              Country("ME", "MNE", "499", "MJ", "EU", "EUR", ".me",
                      "Montenegro", "Podgorica",
                      "#####", "^(\d{5})$", ["382"]),
              Country("MF", "MAF", "663", "RN", "NA", "EUR", ".gp",
                      "Saint Martin", "Marigot",
                      "### ###", "", ["590"]),
              Country("MG", "MDG", "450", "MA", "AF", "MGA", ".mg",
                      "Madagascar", "Antananarivo",
                      "###", "^(\d{3})$", ["261"]),
              Country("MH", "MHL", "584", "RM", "OC", "USD", ".mh",
                      "Marshall Islands", "Majuro",
                      "", "", ["692"]),
              Country("MK", "MKD", "807", "MK", "EU", "MKD", ".mk",
                      "Macedonia", "Skopje",
                      "####", "^(\d{4})$", ["389"]),
              Country("ML", "MLI", "466", "ML", "AF", "XOF", ".ml",
                      "Mali", "Bamako",
                      "", "", ["223"]),
              Country("MM", "MMR", "104", "BM", "AS", "MMK", ".mm",
                      "Myanmar", "Nay Pyi Taw",
                      "#####", "^(\d{5})$", ["95"]),
              Country("MN", "MNG", "496", "MG", "AS", "MNT", ".mn",
                      "Mongolia", "Ulan Bator",
                      "######", "^(\d{6})$", ["976"]),
              Country("MO", "MAC", "446", "MC", "AS", "MOP", ".mo",
                      "Macao", "Macao",
                      "", "", ["853"]),
              Country("MP", "MNP", "580", "CQ", "OC", "USD", ".mp",
                      "Northern Mariana Islands", "Saipan",
                      "", "", ["1-670"]),
              Country("MQ", "MTQ", "474", "MB", "NA", "EUR", ".mq",
                      "Martinique", "Fort-de-France",
                      "#####", "^(\d{5})$", ["596"]),
              Country("MR", "MRT", "478", "MR", "AF", "MRO", ".mr",
                      "Mauritania", "Nouakchott",
                      "", "", ["222"]),
              Country("MS", "MSR", "500", "MH", "NA", "XCD", ".ms",
                      "Montserrat", "Plymouth",
                      "", "", ["1-664"]),
              Country("MT", "MLT", "470", "MT", "EU", "EUR", ".mt",
                      "Malta", "Valletta",
                      "@@@ ###|@@@ ##", "^([A-Z]{3}\d{2}\d?)$", ["356"]),
              Country("MU", "MUS", "480", "MP", "AF", "MUR", ".mu",
                      "Mauritius", "Port Louis",
                      "", "", ["230"]),
              Country("MV", "MDV", "462", "MV", "AS", "MVR", ".mv",
                      "Maldives", "Male",
                      "#####", "^(\d{5})$", ["960"]),
              Country("MW", "MWI", "454", "MI", "AF", "MWK", ".mw",
                      "Malawi", "Lilongwe",
                      "", "", ["265"]),
              Country("MX", "MEX", "484", "MX", "NA", "MXN", ".mx",
                      "Mexico", "Mexico City",
                      "#####", "^(\d{5})$", ["52"]),
              Country("MY", "MYS", "458", "MY", "AS", "MYR", ".my",
                      "Malaysia", "Kuala Lumpur",
                      "#####", "^(\d{5})$", ["60"]),
              Country("MZ", "MOZ", "508", "MZ", "AF", "MZN", ".mz",
                      "Mozambique", "Maputo",
                      "####", "^(\d{4})$", ["258"]),
              Country("NA", "NAM", "516", "WA", "AF", "NAD", ".na",
                      "Namibia", "Windhoek",
                      "", "", ["264"]),
              Country("NC", "NCL", "540", "NC", "OC", "XPF", ".nc",
                      "New Caledonia", "Noumea",
                      "#####", "^(\d{5})$", ["687"]),
              Country("NE", "NER", "562", "NG", "AF", "XOF", ".ne",
                      "Niger", "Niamey",
                      "####", "^(\d{4})$", ["227"]),
              Country("NF", "NFK", "574", "NF", "OC", "AUD", ".nf",
                      "Norfolk Island", "Kingston",
                      "", "", ["672"]),
              Country("NG", "NGA", "566", "NI", "AF", "NGN", ".ng",
                      "Nigeria", "Abuja",
                      "######", "^(\d{6})$", ["234"]),
              Country("NI", "NIC", "558", "NU", "NA", "NIO", ".ni",
                      "Nicaragua", "Managua",
                      "###-###-#", "^(\d{7})$", ["505"]),
              Country("NL", "NLD", "528", "NL", "EU", "EUR", ".nl",
                      "Netherlands", "Amsterdam",
                      "#### @@", "^(\d{4}[A-Z]{2})$", ["31"]),
              Country("NO", "NOR", "578", "NO", "EU", "NOK", ".no",
                      "Norway", "Oslo",
                      "####", "^(\d{4})$", ["47"]),
              Country("NP", "NPL", "524", "NP", "AS", "NPR", ".np",
                      "Nepal", "Kathmandu",
                      "#####", "^(\d{5})$", ["977"]),
              Country("NR", "NRU", "520", "NR", "OC", "AUD", ".nr",
                      "Nauru", "Yaren",
                      "", "", ["674"]),
              Country("NU", "NIU", "570", "NE", "OC", "NZD", ".nu",
                      "Niue", "Alofi",
                      "", "", ["683"]),
              Country("NZ", "NZL", "554", "NZ", "OC", "NZD", ".nz",
                      "New Zealand", "Wellington",
                      "####", "^(\d{4})$", ["64"]),
              Country("OM", "OMN", "512", "MU", "AS", "OMR", ".om",
                      "Oman", "Muscat",
                      "###", "^(\d{3})$", ["968"]),
              Country("PA", "PAN", "591", "PM", "NA", "PAB", ".pa",
                      "Panama", "Panama City",
                      "", "", ["507"]),
              Country("PE", "PER", "604", "PE", "SA", "PEN", ".pe",
                      "Peru", "Lima",
                      "", "", ["51"]),
              Country("PF", "PYF", "258", "FP", "OC", "XPF", ".pf",
                      "French Polynesia", "Papeete",
                      "#####", "^((97)|(98)7\d{2})$", ["689"]),
              Country("PG", "PNG", "598", "PP", "OC", "PGK", ".pg",
                      "Papua New Guinea", "Port Moresby",
                      "###", "^(\d{3})$", ["675"]),
              Country("PH", "PHL", "608", "RP", "AS", "PHP", ".ph",
                      "Philippines", "Manila",
                      "####", "^(\d{4})$", ["63"]),
              Country("PK", "PAK", "586", "PK", "AS", "PKR", ".pk",
                      "Pakistan", "Islamabad",
                      "#####", "^(\d{5})$", ["92"]),
              Country("PL", "POL", "616", "PL", "EU", "PLN", ".pl",
                      "Poland", "Warsaw",
                      "##-###", "^(\d{5})$", ["48"]),
              Country("PM", "SPM", "666", "SB", "NA", "EUR", ".pm",
                      "Saint Pierre and Miquelon", "Saint-Pierre",
                      "#####", "^(97500)$", ["508"]),
              Country("PN", "PCN", "612", "PC", "OC", "NZD", ".pn",
                      "Pitcairn", "Adamstown",
                      "", "", ["870"]),
              Country("PR", "PRI", "630", "RQ", "NA", "USD", ".pr",
                      "Puerto Rico", "San Juan",
                      "#####-####", "^(\d{9})$", ["1-787", "1-939"]),
              Country("PS", "PSE", "275", "WE", "AS", "ILS", ".ps",
                      "Palestinian Territory", "East Jerusalem",
                      "", "", ["970"]),
              Country("PT", "PRT", "620", "PO", "EU", "EUR", ".pt",
                      "Portugal", "Lisbon",
                      "####-###", "^(\d{7})$", ["351"]),
              Country("PW", "PLW", "585", "PS", "OC", "USD", ".pw",
                      "Palau", "Melekeok",
                      "96940", "^(96940)$", ["680"]),
              Country("PY", "PRY", "600", "PA", "SA", "PYG", ".py",
                      "Paraguay", "Asuncion",
                      "####", "^(\d{4})$", ["595"]),
              Country("QA", "QAT", "634", "QA", "AS", "QAR", ".qa",
                      "Qatar", "Doha",
                      "", "", ["974"]),
              Country("RE", "REU", "638", "RE", "AF", "EUR", ".re",
                      "Reunion", "Saint-Denis",
                      "#####", "^((97)|(98)(4|7|8)\d{2})$", ["262"]),
              Country("RO", "ROU", "642", "RO", "EU", "RON", ".ro",
                      "Romania", "Bucharest",
                      "######", "^(\d{6})$", ["40"]),
              Country("RS", "SRB", "688", "RI", "EU", "RSD", ".rs",
                      "Serbia", "Belgrade",
                      "######", "^(\d{6})$", ["381"]),
              Country("RU", "RUS", "643", "RS", "EU", "RUB", ".ru",
                      "Russia", "Moscow",
                      "######", "^(\d{6})$", ["7"]),
              Country("RW", "RWA", "646", "RW", "AF", "RWF", ".rw",
                      "Rwanda", "Kigali",
                      "", "", ["250"]),
              Country("SA", "SAU", "682", "SA", "AS", "SAR", ".sa",
                      "Saudi Arabia", "Riyadh",
                      "#####", "^(\d{5})$", ["966"]),
              Country("SB", "SLB", "090", "BP", "OC", "SBD", ".sb",
                      "Solomon Islands", "Honiara",
                      "", "", ["677"]),
              Country("SC", "SYC", "690", "SE", "AF", "SCR", ".sc",
                      "Seychelles", "Victoria",
                      "", "", ["248"]),
              Country("SD", "SDN", "729", "SU", "AF", "SDG", ".sd",
                      "Sudan", "Khartoum",
                      "#####", "^(\d{5})$", ["249"]),
              Country("SS", "SSD", "728", "OD", "AF", "SSP", "",
                      "South Sudan", "Juba",
                      "", "", ["211"]),
              Country("SE", "SWE", "752", "SW", "EU", "SEK", ".se",
                      "Sweden", "Stockholm",
                      "SE-### ##", "^(?:SE)*(\d{5})$", ["46"]),
              Country("SG", "SGP", "702", "SN", "AS", "SGD", ".sg",
                      "Singapore", "Singapur",
                      "######", "^(\d{6})$", ["65"]),
              Country("SH", "SHN", "654", "SH", "AF", "SHP", ".sh",
                      "Saint Helena", "Jamestown",
                      "STHL 1ZZ", "^(STHL1ZZ)$", ["290"]),
              Country("SI", "SVN", "705", "SI", "EU", "EUR", ".si",
                      "Slovenia", "Ljubljana",
                      "SI- ####", "^(?:SI)*(\d{4})$", ["386"]),
              Country("SJ", "SJM", "744", "SV", "EU", "NOK", ".sj",
                      "Svalbard and Jan Mayen", "Longyearbyen",
                      "", "", ["47"]),
              Country("SK", "SVK", "703", "LO", "EU", "EUR", ".sk",
                      "Slovakia", "Bratislava",
                      "###  ##", "^(\d{5})$", ["421"]),
              Country("SL", "SLE", "694", "SL", "AF", "SLL", ".sl",
                      "Sierra Leone", "Freetown",
                      "", "", ["232"]),
              Country("SM", "SMR", "674", "SM", "EU", "EUR", ".sm",
                      "San Marino", "San Marino",
                      "4789#", "^(4789\d)$", ["378"]),
              Country("SN", "SEN", "686", "SG", "AF", "XOF", ".sn",
                      "Senegal", "Dakar",
                      "#####", "^(\d{5})$", ["221"]),
              Country("SO", "SOM", "706", "SO", "AF", "SOS", ".so",
                      "Somalia", "Mogadishu",
                      "@@  #####", "^([A-Z]{2}\d{5})$", ["252"]),
              Country("SR", "SUR", "740", "NS", "SA", "SRD", ".sr",
                      "Suriname", "Paramaribo",
                      "", "", ["597"]),
              Country("ST", "STP", "678", "TP", "AF", "STD", ".st",
                      "Sao Tome and Principe", "Sao Tome",
                      "", "", ["239"]),
              Country("SV", "SLV", "222", "ES", "NA", "USD", ".sv",
                      "El Salvador", "San Salvador",
                      "CP ####", "^(?:CP)*(\d{4})$", ["503"]),
              Country("SX", "SXM", "534", "NN", "NA", "ANG", ".sx",
                      "Sint Maarten", "Philipsburg",
                      "", "", ["599"]),
              Country("SY", "SYR", "760", "SY", "AS", "SYP", ".sy",
                      "Syria", "Damascus",
                      "", "", ["963"]),
              Country("SZ", "SWZ", "748", "WZ", "AF", "SZL", ".sz",
                      "Swaziland", "Mbabane",
                      "@###", "^([A-Z]\d{3})$", ["268"]),
              Country("TC", "TCA", "796", "TK", "NA", "USD", ".tc",
                      "Turks and Caicos Islands", "Cockburn Town",
                      "TKCA 1ZZ", "^(TKCA 1ZZ)$", ["1-649"]),
              Country("TD", "TCD", "148", "CD", "AF", "XAF", ".td",
                      "Chad", "N'Djamena",
                      "", "", ["235"]),
              Country("TF", "ATF", "260", "FS", "AN", "EUR", ".tf",
                      "French Southern Territories", "Port-aux-Francais",
                      "", "", [""]),
              Country("TG", "TGO", "768", "TO", "AF", "XOF", ".tg",
                      "Togo", "Lome",
                      "", "", ["228"]),
              Country("TH", "THA", "764", "TH", "AS", "THB", ".th",
                      "Thailand", "Bangkok",
                      "#####", "^(\d{5})$", ["66"]),
              Country("TJ", "TJK", "762", "TI", "AS", "TJS", ".tj",
                      "Tajikistan", "Dushanbe",
                      "######", "^(\d{6})$", ["992"]),
              Country("TK", "TKL", "772", "TL", "OC", "NZD", ".tk",
                      "Tokelau", "",
                      "", "", ["690"]),
              Country("TL", "TLS", "626", "TT", "OC", "USD", ".tl",
                      "East Timor", "Dili",
                      "", "", ["670"]),
              Country("TM", "TKM", "795", "TX", "AS", "TMT", ".tm",
                      "Turkmenistan", "Ashgabat",
                      "######", "^(\d{6})$", ["993"]),
              Country("TN", "TUN", "788", "TS", "AF", "TND", ".tn",
                      "Tunisia", "Tunis",
                      "####", "^(\d{4})$", ["216"]),
              Country("TO", "TON", "776", "TN", "OC", "TOP", ".to",
                      "Tonga", "Nuku'alofa",
                      "", "", ["676"]),
              Country("TR", "TUR", "792", "TU", "AS", "TRY", ".tr",
                      "Turkey", "Ankara",
                      "#####", "^(\d{5})$", ["90"]),
              Country("TT", "TTO", "780", "TD", "NA", "TTD", ".tt",
                      "Trinidad and Tobago", "Port of Spain",
                      "", "", ["1-868"]),
              Country("TV", "TUV", "798", "TV", "OC", "AUD", ".tv",
                      "Tuvalu", "Funafuti",
                      "", "", ["688"]),
              Country("TW", "TWN", "158", "TW", "AS", "TWD", ".tw",
                      "Taiwan", "Taipei",
                      "#####", "^(\d{5})$", ["886"]),
              Country("TZ", "TZA", "834", "TZ", "AF", "TZS", ".tz",
                      "Tanzania", "Dodoma",
                      "", "", ["255"]),
              Country("UA", "UKR", "804", "UP", "EU", "UAH", ".ua",
                      "Ukraine", "Kiev",
                      "#####", "^(\d{5})$", ["380"]),
              Country("UG", "UGA", "800", "UG", "AF", "UGX", ".ug",
                      "Uganda", "Kampala",
                      "", "", ["256"]),
              Country("UM", "UMI", "581", "", "OC", "USD", ".um",
                      "United States Minor Outlying Islands", "",
                      "", "", ["1"]),
              Country("US", "USA", "840", "US", "NA", "USD", ".us",
                      "United States", "Washington",
                      "#####-####", "^(\d{9})$", ["1"]),
              Country("UY", "URY", "858", "UY", "SA", "UYU", ".uy",
                      "Uruguay", "Montevideo",
                      "#####", "^(\d{5})$", ["598"]),
              Country("UZ", "UZB", "860", "UZ", "AS", "UZS", ".uz",
                      "Uzbekistan", "Tashkent",
                      "######", "^(\d{6})$", ["998"]),
              Country("VA", "VAT", "336", "VT", "EU", "EUR", ".va",
                      "Vatican", "Vatican City",
                      "", "", ["379"]),
              Country("VC", "VCT", "670", "VC", "NA", "XCD", ".vc",
                      "Saint Vincent and the Grenadines", "Kingstown",
                      "", "", ["1-784"]),
              Country("VE", "VEN", "862", "VE", "SA", "VEF", ".ve",
                      "Venezuela", "Caracas",
                      "####", "^(\d{4})$", ["58"]),
              Country("VG", "VGB", "092", "VI", "NA", "USD", ".vg",
                      "British Virgin Islands", "Road Town",
                      "", "", ["1-284"]),
              Country("VI", "VIR", "850", "VQ", "NA", "USD", ".vi",
                      "U.S. Virgin Islands", "Charlotte Amalie",
                      "", "", ["1-340"]),
              Country("VN", "VNM", "704", "VM", "AS", "VND", ".vn",
                      "Vietnam", "Hanoi",
                      "######", "^(\d{6})$", ["84"]),
              Country("VU", "VUT", "548", "NH", "OC", "VUV", ".vu",
                      "Vanuatu", "Port Vila",
                      "", "", ["678"]),
              Country("WF", "WLF", "876", "WF", "OC", "XPF", ".wf",
                      "Wallis and Futuna", "Mata Utu",
                      "#####", "^(986\d{2})$", ["681"]),
              Country("WS", "WSM", "882", "WS", "OC", "WST", ".ws",
                      "Samoa", "Apia",
                      "", "", ["685"]),
              Country("YE", "YEM", "887", "YM", "AS", "YER", ".ye",
                      "Yemen", "Sanaa",
                      "", "", ["967"]),
              Country("YT", "MYT", "175", "MF", "AF", "EUR", ".yt",
                      "Mayotte", "Mamoudzou",
                      "#####", "^(\d{5})$", ["262"]),
              Country("ZA", "ZAF", "710", "SF", "AF", "ZAR", ".za",
                      "South Africa", "Pretoria",
                      "####", "^(\d{4})$", ["27"]),
              Country("ZM", "ZMB", "894", "ZA", "AF", "ZMK", ".zm",
                      "Zambia", "Lusaka",
                      "#####", "^(\d{5})$", ["260"]),
              Country("ZW", "ZWE", "716", "ZI", "AF", "ZWL", ".zw",
                      "Zimbabwe", "Harare",
                      "", "", ["263"]),
              Country("CS", "SCG", "891", "YI", "EU", "RSD", ".cs",
                      "Serbia and Montenegro", "Belgrade",
                      "#####", "^(\d{5})$", ["381"]),
              Country("AN", "ANT", "530", "NT", "NA", "ANG", ".an",
                      "Netherlands Antilles", "Willemstad",
                      "", "", ["599"])])
